# Generated by Django 4.2.1 on 2023-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
