# Generated by Django 4.0.3 on 2023-05-13 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('favorites', models.BooleanField(default=False)),
                ('folder_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(max_length=100)),
                ('memo', models.TextField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('removed', models.BooleanField(default=False)),
                ('s3key', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
    ]
