# Generated by Django 4.2 on 2023-05-16 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('favorites', models.BooleanField(default=False)),
                ('folder_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('memo', models.TextField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('removed', models.BooleanField(default=False)),
                ('s3key', models.CharField(max_length=255, null=True)),
                ('clicked', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'managed': True,
            },
        ),
    ]
