# Generated by Django 4.0.3 on 2023-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='id',
        ),
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
